[0m18:23:44.125161 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c396eccbc10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c396f25a750>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c396ee62ed0>]}


============================== 18:23:44.127094 | 8dc0b010-4090-49c4-b675-4de05bc30cc0 ==============================
[0m18:23:44.127094 [info ] [MainThread]: Running with dbt=1.9.2
[0m18:23:44.127432 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/ivs/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m18:23:44.127743 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/ivs/Proggeprosjekter/nve_data_analytics_project/src/nve_statistics_transform/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:23:44.128312 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.030798769, "process_in_blocks": "0", "process_kernel_time": 0.145584, "process_mem_max_rss": "95128", "process_out_blocks": "8", "process_user_time": 0.90257}
[0m18:23:44.128560 [debug] [MainThread]: Command `dbt run` failed at 18:23:44.128505 after 0.03 seconds
[0m18:23:44.128769 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c3972a176d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c396ee62f10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c396ee62e10>]}
[0m18:23:44.128984 [debug] [MainThread]: Flushing usage events
[0m18:23:44.522407 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:25:14.153299 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c10037add90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c1004e192d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c1004e36490>]}


============================== 18:25:14.155337 | 878de7c9-39c9-4b02-9a0d-5917e76b13a1 ==============================
[0m18:25:14.155337 [info ] [MainThread]: Running with dbt=1.9.2
[0m18:25:14.155647 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/home/ivs/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m18:25:14.155958 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/ivs/Proggeprosjekter/nve_data_analytics_project/src/transform/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:25:14.156535 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.03176937, "process_in_blocks": "0", "process_kernel_time": 0.157667, "process_mem_max_rss": "94804", "process_out_blocks": "16", "process_user_time": 0.911587}
[0m18:25:14.156788 [debug] [MainThread]: Command `dbt run` failed at 18:25:14.156733 after 0.03 seconds
[0m18:25:14.157019 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c10037b9510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c100751b6d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7c100394d590>]}
[0m18:25:14.157233 [debug] [MainThread]: Flushing usage events
[0m18:25:14.568368 [debug] [MainThread]: An error was encountered while trying to flush usage events
